name: Android Release Build

on:
  push:
    tags:
      - onlyBuild
    branches:
      - develop

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Decode keystore.jks
        run: |
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Decode google-services.json
        run: |
          mkdir -p app
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew clean bundleRelease \
          -PKEYSTORE_PASSWORD=${{ secrets.RELEASE_KEYSTORE_PASSWORD }} \
          -PKEY_ALIAS=${{ secrets.RELEASE_KEYSTORE_ALIAS }} \
          -PKEY_PASSWORD=${{ secrets.RELEASE_KEY_PASSWORD }}
