name: Firebase Remote Config Update

on:
  push:
    tags:
      - 'VerUpdate*'  # 태그가 VerUpdate로 시작할 때만 실행

jobs:
  update-remote-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install latest Firebase CLI
        run: npm install -g firebase-tools

      - name: Decode Firebase Service Account JSON
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > firebase-adminsdk.json

      - name: Validate Firebase Remote Config template
        run: |
          firebase remoteconfig:template:validate ./firebase/remote-config.json --project $(jq -r '.project_id' firebase-adminsdk.json)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-adminsdk.json

      - name: Publish Firebase Remote Config template
        run: |
          firebase remoteconfig:template:publish ./firebase/remote-config.json --project $(jq -r '.project_id' firebase-adminsdk.json)
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-adminsdk.json
