name: Update Firebase Remote Config

on:
  push:
    tags:
      - 'VerUpdate*' # 태그가 VerUpdate로 시작할 때만 트리거됨

jobs:
  update-remote-config:
    name: Validate & Publish Firebase Remote Config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Firebase 서비스 계정 키 디코딩 (Secrets에서 가져옴)
      - name: Decode Firebase Admin SDK JSON
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 -d > firebase-adminsdk.json

      # 2. Firebase CLI 설치
      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      # 3. GOOGLE_APPLICATION_CREDENTIALS 환경변수 설정
      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: echo "GOOGLE_APPLICATION_CREDENTIALS=$PWD/firebase-adminsdk.json" >> $GITHUB_ENV

      # 4. Remote Config 템플릿 유효성 검사
      - name: Validate Remote Config template
        run: |
          PROJECT_ID=$(jq -r '.project_id' firebase-adminsdk.json)
          firebase remoteconfig:template:validate \
            --project "$PROJECT_ID" \
            --template ./firebase/remote-config.json

      # 5. Remote Config 템플릿 개시 (배포)
      - name: Publish Remote Config template
        run: |
          PROJECT_ID=$(jq -r '.project_id' firebase-adminsdk.json)
          firebase remoteconfig:template:publish \
            --project "$PROJECT_ID" \
            --template ./firebase/remote-config.json
