name: Firebase Remote Config Update

on:
  push:
    tags:
      - 'VerUpdate*'  # 'VerUpdate'로 시작하는 태그가 푸시되면 실행

jobs:
  update-remote-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Decode Firebase Admin SDK JSON
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > firebase-adminsdk.json

      - name: Authenticate with Firebase
        run: firebase auth:login:ci --token "$(jq -r '.private_key' firebase-adminsdk.json)" || echo "Token not needed with service account"

      - name: Upload Remote Config JSON
        run: |
          firebase remoteconfig:versions:list --project "$(jq -r '.project_id' firebase-adminsdk.json)"
          firebase remoteconfig:template:validate --project "$(jq -r '.project_id' firebase-adminsdk.json)" --template ./firebase/remote-config.json
          firebase remoteconfig:template:publish --project "$(jq -r '.project_id' firebase-adminsdk.json)" --template ./firebase/remote-config.json
