name: Android Release Build and Firebase App Distribution

on:
  push:
    tags:
      - 'FBv*' # FBv로 시작하는 태그가 푸시될 때만 워크플로우 실행 (예: FBv1.0.4)

jobs:
  build:
    name: Build Release APK and Upload to Firebase App Distribution
    runs-on: ubuntu-latest

    steps:
    # GitHub 리포지토리에서 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

    # JDK 17 설치 (Android 빌드 도구 사용을 위해 필요)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
    # keystore 파일 base64 디코딩 후 저장 (앱 서명에 사용)
      - name: Decode keystore.jks
        run: |
          mkdir -p app/jks
          echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 -d > app/jks/saveurlkey.jks
          
    # google-services.json 파일 base64 디코딩 후 저장 (Firebase 연동에 필요)
      - name: Decode google-services.json
        run: |
          mkdir -p app
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

    # gradlew 실행 권한 부여
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

    # 릴리즈 APK 빌드 (keystore 정보 환경변수로 전달)
      - name: Build Release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
          KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
        run: ./gradlew clean assembleRelease

    # Firebase CLI 설치 (배포를 위해 필요)
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

    # Firebase 서비스 계정 JSON을 파일로 저장
      - name: Save Firebase Service Account JSON
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > ${{ github.workspace }}/service-account.json

    # Firebase App Distribution에 APK 업로드
      - name: Upload APK to Firebase App Distribution
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/service-account.json
        run: |
          firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk \
            --app ${{ secrets.FIREBASE_APP_ID }}
